[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js routing - SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes (commented out for static export)
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "esbuild"

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js specific redirects
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# API redirects (commented out for static export)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200 