[build]
  command = "cp next.config.netlify.mjs next.config.mjs && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Netlify will handle API routes automatically
# No need for manual redirects

# لا نحتاج functions لأن Next.js يتعامل مع API routes تلقائياً
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://office-management-system-v82i.onrender.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 